spring:
  profiles:
    active: druid

# MyBatis-plus配置
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 日志打印到控制台
  #    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl  # 关闭日志打印
  global-config:
    db-config:
      # 雪花算法生成 ID
      id-type: ASSIGN_ID
